### ISSUE TITLE
How do I add accounts to be used?

### ISSUE THREAD

**Issue by Dulappy** [Edouard127/reddit-placebot-2023#1]
I'm assuming I have to place it in the `users.json.rename` file and rename it to `users.json`, but I'm not sure what format the credentials should be in.

**Comment by Edouard127** [comment]
Yes `[{"username": "", "password": ""}]`

But, read the repo info
There's some bugs with it and it's not quite ready, I'm searching for people to help me

**Comment by Dulappy** [comment]
I wish I could help you, but sadly I don't know anything about golang. Maybe you could try looking into some of the scripts from last year to see how they worked. Even though most of them are in Python, there's gotta be a lot of stuff that's universal in there too.

**Comment by Edouard127** [comment]
Right now everything should work, can you try and give me a feedback ?

**Comment by LookItsAndy** [comment]
Were you able to get the workers to place pixels?

**Comment by Edouard127** [comment]
> Were you able to get the workers to place pixels?

I was once, but reddit is pretty harsh on the shadowbans

**Comment by LookItsAndy** [comment]
Where do I input the coordinates for an image?

**Comment by Edouard127** [comment]
> 

-minX and -minY arguments
This point will be the top left of your image

**Comment by LookItsAndy** [comment]
I was able to get the bot to work but I can see that the pixels are not being placed even though there is a cooldown. Does the bot always start in the top left corner?

**Comment by Edouard127** [comment]
> I was able to get the bot to work but I can see that the pixels are not being placed even though there is a cooldown. Does the bot always start in the top left corner?

No, since It's multithreaded, a client could place before the other, it's not synchronized

**Comment by yahyaalx** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x78f77a]

goroutine 53 [running]:
golang.org/x/net/websocket.(*Conn).Write(0x86d900?, {0xc00016ec00, 0x537, 0x580})
        /home/go/pkg/mod/golang.org/x/net@v0.12.0/websocket/websocket.go:222 +0x5a
main.(*Client).connect(0xc000110ab0, 0xc000128180)
        /home/desktop/reddit-placebot-2023/client.go:152 +0x248
created by main.(*Client).Login
        /home/desktop/reddit-placebot-2023/client.go:80 +0x62a

keep getting this error

**Comment by NoctisNerdViking** [comment]
i also having problems
2023-07-22T04:09:49.035-0300    ERROR   reddit-placebot-2023-master/client.go:62        Login failed    {"username": "", "username": ""}
main.(*Client).Login
and he resets my users.jason

**Comment by Dulappy** [comment]
Logins work fine, `users.json` also gets updated just fine, but the client seems to be completely ignoring `minX` and `minY` values, as well as trying to start building from `(0, 1000)` up, giving me an `invalid coordinate 'Y'` error. For example, it would try to place image pixel `(9, 2)` at canvas coordinate `(9, 998)`.

**Comment by Louisbertelsmann** [comment]
How do I know where the bot is placing the pixels in the terminal? I don't see pixels being placed on the canvas at the specified location, but it seems that it's working. There are three numbers in the terminal: Placing pixel {13 28} {255 56 129} 4 {13 972}

**Comment by Edouard127** [comment]
> How do I know where the bot is placing the pixels in the terminal? I don't see pixels being placed on the canvas at the specified location, but it seems that it's working. There are three numbers in the terminal: Placing pixel {13 28} {255 56 129} 4 {13 972}

Point - Color - API Point

**Comment by Edouard127** [comment]
> Logins work fine, `users.json` also gets updated just fine, but the client seems to be completely ignoring `minX` and `minY` values, as well as trying to start building from `(0, 1000)` up, giving me an `invalid coordinate 'Y'` error. For example, it would try to place image pixel `(9, 2)` at canvas coordinate `(9, 998)`.

5aa34fd

**Comment by Edouard127** [comment]
> panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x78f77a]
> 
> goroutine 53 [running]: golang.org/x/net/websocket.(*Conn).Write(0x86d900?, {0xc00016ec00, 0x537, 0x580}) /home/go/pkg/mod/golang.org/x/net@v0.12.0/websocket/websocket.go:222 +0x5a main.(*Client).connect(0xc000110ab0, 0xc000128180) /home/desktop/reddit-placebot-2023/client.go:152 +0x248 created by main.(*Client).Login /home/desktop/reddit-placebot-2023/client.go:80 +0x62a
> 
> keep getting this error

a4da007 you should be able to get more information about what's causing the issue

**Comment by LookItsAndy** [comment]
It's still saying pixels are being placed however I can't see them on the canvas

**Comment by Edouard127** [comment]
> It's still saying pixels are being placed however I can't see them on the canvas

I fixed the points not being registered and now it's giving more info about the user
Shadow bans, r/place bans and unverified accounts
292e12e

**Comment by LookItsAndy** [comment]
> 

My account isn't shadowbanned though. I just placed a pixel right now and I was able to see it on my phone too.

**Comment by CCeriseGD** [comment]
i get this error

```
panic: websocket.Dial wss://gql-realtime-2.reddit.com/query: dial tcp: lookup gql-realtime-2.reddit.com on 127.0.0.53:53: socks connect udp 127.0.0.1:9050->127.0.0.53:53: network not implemented

goroutine 1 [running]:
main.readClients(0x3b9aca00?, 0xc00011c810)
    /home/ccerisegd/place/reddit-placebot-2023/main.go:102 +0xde7
main.main()
    /home/ccerisegd/place/reddit-placebot-2023/main.go:26 +0x30e
```

**Comment by Edouard127** [comment]
> > 
> 
> 
> 
> My account isn't shadowbanned though. I just placed a pixel manually right now and I was able to see it on my phone too.

This year reddit r/place is very buggy 
I request the information of a pixel and it doesn't give the right information 
Usually I had this issue with proxies, but went away with the tor node
I will need to investigate more

**Comment by Edouard127** [comment]
> socks connect udp 127.0.0.1:9050->127.0.0.53:53: network not implemented

Are you running the tor node ?

**Comment by CCeriseGD** [comment]
> > socks connect udp 127.0.0.1:9050->127.0.0.53:53: network not implemented
> 
> Are you running the tor node ?

yes

**Comment by Edouard127** [comment]
> 127.0.0.53:53

Are you using linux

**Comment by CCeriseGD** [comment]
> Are you using linux

yes

**Comment by Edouard127** [comment]
> socks connect udp 127.0.0.1:9050->127.0.0.53:53: network not implemented

Check your dns resolver

**Comment by CCeriseGD** [comment]
> Check your dns resolver

it seems to be fine

**Comment by Edouard127** [comment]
> > Check your dns resolver
> 
> it seems to be fine

Since I do not have a linux machine available I cannot debug the issue
