### ISSUE TITLE
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x10f3a76]

### ISSUE THREAD

**Issue by brafaz** [Edouard127/reddit-placebot-2023#100]
C:\Users\BraFaz\Desktop\reddit-placebot-2023-master>.\redditplacebot -minX=64 -minY=64
Waiting for login to finish...
2023-07-25T22:04:24.791+0800    INFO    reddit-placebot-2023-master/client.go:84        Login successful        {"username": "Hot_Reveal_1469"}
Login finished!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x10f3a76]

goroutine 1 [running]:
main.(*Board).GetDifferentData(0xc000220140)
        C:/Users/BraFaz/Desktop/reddit-placebot-2023-master/board.go:43 +0xb6
main.(*Worker).Run(0xc000220180)
        C:/Users/BraFaz/Desktop/reddit-placebot-2023-master/worker.go:37 +0x58
main.main()
        C:/Users/BraFaz/Desktop/reddit-placebot-2023-master/main.go:47 +0x5cf

**Comment by yavuzilyas** [comment]
same problem

**Comment by r4ngu** [comment]
guys please fucking read closed issues, read thos #95

**Comment by brafaz** [comment]
> guys please fucking read closed issues, read this #95
not working
