### ISSUE TITLE
Problem with tor

### ISSUE THREAD

**Issue by lammamadelmanu** [Edouard127/reddit-placebot-2023#101]
I installed tor on linux, then afterwards i changed the torrc file and i pasted in the circuit script. Then once i start tor by typing on the terminal just "tor" it runs tor. Then if I go on my browser and I type whats my ip it gives me the same ip I had before. My ip got banned and i'm trying to make new accounts but tor isnt working at all.

**Comment by Edouard127** [comment]
> Then if I go on my browser

Read the tutorial, you're not supposed to use the *browser*
