### ISSUE TITLE
Stuck on Waiting for login to finish...

### ISSUE THREAD

**Issue by Fiteropp** [Edouard127/reddit-placebot-2023#13]

**Comment by Edouard127** [comment]
Need more info

**Comment by gigantino** [comment]
@Edouard127 having the same issue. I just put in the file this
```
[{"username: "", "password": ""}]
```
Yet it doesn't log anything in the console and doesn't seem to be working

**Comment by Edouard127** [comment]
You have to use an actual account

**Comment by gigantino** [comment]
> You have to use an actual account

Obviously, I did.
Anyhow, I now managed to make it work. It was a network issue, but it didn't log anything.

**Comment by Edouard127** [comment]
> > You have to use an actual account
> 
> Obviously, I did. Anyhow, I now managed to make it work. It was a network issue, but it didn't log anything.

It's missing a " in your json, now it notify you if there's a bad json config
