### ISSUE TITLE
what it this ?

### ISSUE THREAD

**Issue by brafaz** [Edouard127/reddit-placebot-2023#14]
i placing from browser this account,no shadow ban
but start bots 
 INFO    reddit-placebot-2023-master/client.go:307       Account has been shadow banned from r/place

**Comment by Edouard127** [comment]
> i placing from browser this account,no shadow ban but start bots INFO reddit-placebot-2023-master/client.go:307 Account has been shadow banned from r/place

I'm relaying on the reddit websocket to check for shadow ban, but they've fucked their thing
Or It's because or a api point issue

Try somewhere else

**Comment by Edouard127** [comment]
> i placing from browser this account,no shadow ban but start bots INFO reddit-placebot-2023-master/client.go:307 Account has been shadow banned from r/place

Could you tell me where you've tried to place a pixel ?

**Comment by brafaz** [comment]
in different places

**Comment by brafaz** [comment]
could it be a color issue ?

**Comment by Edouard127** [comment]
Tell me what point you initially tried when making the issue

**Comment by brafaz** [comment]
how to make sure that pixels are placed correctly and always ?

**Comment by Edouard127** [comment]
> how to make sure that pixels are placed correctly and always ?
https://github.com/Edouard127/reddit-placebot-2023/blob/7ce9373c5452c0770bc1880d08487c530c4ce796/client.go#L306

**Comment by brafaz** [comment]
okey
