### ISSUE TITLE
Stuck on Waiting for board data

### ISSUE THREAD

**Issue by AdamEXu** [Edouard127/reddit-placebot-2023#19]
How long is it suppose to take? I have wait 2 minutes. Should r/place take this long to load? When I open in my chrome it is fine. Is it because Tor need another computer to run? Thanks!

**Comment by Edouard127** [comment]
> How long is it suppose to take? I have wait 2 minutes. Should r/place take this long to load? When I open in my chrome it is fine. Is it because Tor need another computer to run? Thanks!

I can reproduce the issue when there's no accounts in the users.json file

**Comment by Edouard127** [comment]
9d54c59

**Comment by AdamEXu** [comment]
I have the username and password inside of data/users.json. It is the following:
`[{"username: "Careless-Rhubarb-79", "password": "******"}, {"username: "Itchy_Bug7367", "password": "******"}]`
Is that the wrong way to do?

**Comment by AdamEXu** [comment]
I replaced the real password with ****** for obvious reason.

**Comment by Edouard127** [comment]
> I have the username and password inside of data/users.json. It is the following: `[{"username: "Careless-Rhubarb-79", "password": "******"}, {"username: "Itchy_Bug7367", "password": "******"}]` Is that the wrong way to do?

yes

**Comment by AdamEXu** [comment]
How can I fix it then?

**Comment by AdamEXu** [comment]
In the real code, the password is the password to the Reddit account I create. When I run, it still says `Error read users.json. Is empty?`

**Comment by AdamEXu** [comment]
Do I need to put something around it in the JSON file?

**Comment by Edouard127** [comment]
Use this commit b61bfb5

**Comment by Edouard127** [comment]
> I have the username and password inside of data/users.json. It is the following: `[{"username: "Careless-Rhubarb-79", "password": "******"}, {"username: "Itchy_Bug7367", "password": "******"}]` Is that the wrong way to do?

You're missing a " in your json

**Comment by Fiteropp** [comment]
What I am doing wrong? When I start redditplacebot, it just stops on "Waiting for login to finish…" I tried waiting for about half an hour, but nothing happened…

**Comment by Edouard127** [comment]
> What I am doing wrong? When I start redditplacebot, it just stops on "Waiting for login to finish…" I tried waiting for about half an hour, but nothing happened…

Use the latest commit and try again

**Comment by Fiteropp** [comment]
Still doesn't seem to work. But does it matter where do you put a Tor Expert folder?

**Comment by Edouard127** [comment]
> Still doesn't seem to work. But does it matter where do you put a Tor Expert folder?

I put it in my C: drive and then I put the Tor/tor into my environment variables in windows

**Comment by Fiteropp** [comment]
Do you start placebot with PowerShell?

**Comment by Edouard127** [comment]
> Do you start placebot with PowerShell?

You run the exe you've build or go run .

**Comment by Fiteropp** [comment]
unfortunately it still doesn't get over "Waiting login to finish..."

**Comment by Edouard127** [comment]
> unfortunately it still doesn't get over "Waiting login to finish..."

Have you updated the json file with the missing character ?

**Comment by Fiteropp** [comment]
> > unfortunately it still doesn't get over "Waiting login to finish..."
> 
> Have you updated the json file with the missing character ?

Yes

[
    {
        "username": "Successful-Map7176",
        "password": "******"
    },
    {
        "username": "Adept-Race-8083",
        "password": "********"
    }
]
Is everything right?

**Comment by treviskjellberg22** [comment]
Also getting the error "panic: I could not decode the users.json file: invalid character 'N' after object key"
I believe it's formatted fine

[{"username": "SacrifiedGoat", "password": "*****"}, {"username: "NewAvatar22", "password": "*****"}]

**Comment by treviskjellberg22** [comment]
New error:

Waiting for login to finish...
Error receiving message from socket EOF
2023-07-22T16:31:17.920-0700    INFO    reddit-placebot-2023-master/client.go:82        Login successful        {"username": "SacrifiedGoat"}
2023-07-22T16:31:35.233-0700    INFO    reddit-placebot-2023-master/client.go:82        Login successful        {"username": "NewAvatar22"}
Error receiving message from socket EOF

**Comment by Edouard127** [comment]
The socket eof is normal, it's taking too long to login to the wss, just restart the program and it will work
