### ISSUE TITLE
Error placing pixel

### ISSUE THREAD

**Issue by TheScreem** [Edouard127/reddit-placebot-2023#21]
Hello, i have a message when my user try to place a pixel.
I have only worker account and i when to place a square of 10 px

This is the error : 
INFO    reddit-placebot-2023/client.go:311      Error placing pixel     {"username": "Own-Bag-3290", "message": "Ratelimited"}

Thanks you !

**Comment by Edouard127** [comment]
The account is rate limited, you have to wait until you can place a pixel

**Comment by TheScreem** [comment]
It's the first time so i want to try it once.
But it's stuck at "Placing pixel" 
Placing pixel {-444 -358} {180 74 192} 1 {56 642}

**Comment by Edouard127** [comment]
> It's the first time so i want to try it once. But it's stuck at "Placing pixel" Placing pixel {-444 -358} {180 74 192} 1 {56 642}
> 
> And the pixel it's not placed unfortunalty

If there's nothing after Placing pixel then it placed the pixel successfully

**Comment by TheScreem** [comment]
Yes it's seems to work ! 
Thanks you for your work !

**Comment by Edouard127** [comment]
It might break for no reason so watch out

**Comment by TheScreem** [comment]
Ok
