### ISSUE TITLE
 Account has been shadow banned from r/place 

### ISSUE THREAD

**Issue by anelfer** [Edouard127/reddit-placebot-2023#24]
an error is thrown, but if you go to the account and put it, it is put (it can be seen from another account)

**Comment by r4ngu** [comment]
Reddit bots detected your bot account. It basically means you cannot add pixels onto r/place no more.

**Comment by anelfer** [comment]
I understand, but why if you log in from the browser and put your hands - everything is fine?

**Comment by r4ngu** [comment]
I'm really not sure.

**Comment by r4ngu** [comment]
But a possible explanation it's possibly because of... the Reddit Bots detect in-human actions? Might ask Edouard127 for a possible explanation

**Comment by Edouard127** [comment]
https://www.reddit.com/r/RedditEng/comments/wro64p/how_we_built_rplace_2022_bots_and_safety/

**Comment by Edouard127** [comment]
8d7e1c1 This should reduce the chances of getting shadowbanned
