### ISSUE TITLE
Pixels have wrong color

### ISSUE THREAD

**Issue by BrunoZockt** [Edouard127/reddit-placebot-2023#28]
For some reason pixels are cyan instead of black. Whether I use 16-color or 256-color bmp doesn't change this.

**Comment by rodomils** [comment]
Happened to me too, 
![image](https://github.com/Edouard127/reddit-placebot-2023/assets/117560269/fbb687ad-7ccf-4bb9-9fa0-0bd2d546216f)
This should've been a blue one.

**Comment by Edouard127** [comment]
It doesn't place pixels in a synchronous way
It could start with the 78th pixel in the image

**Comment by rodomils** [comment]
There isnt any grey pixels in the image im loading, thats why i thought it was an error, but ill try again, im with 90 accounts and it will take a lot to load ig

**Comment by Niximkk** [comment]
Same here

**Comment by AdamEXu** [comment]
I have dark green pixels turning cyan for some reason, I haven't tried picking the hex out of r/place yet so I'm going to try that first.

**Comment by AdamEXu** [comment]
Oh, it seems you have to use the exact hex code! I haven't thoroughly tested yet though.

**Comment by AdamEXu** [comment]
Actually orange isn't working for me.

**Comment by AdamEXu** [comment]
Can you give the exact hex codes for the working color? I only need 5 colors:
Dark green, light green, yellow, orange, and light gray! Black and white are already working fine.

**Comment by Edouard127** [comment]
var Colors = map[int]Color{
	0:  hexToRGB("#6D001A"), // Darkest Red
	1:  hexToRGB("#BE0039"), // Dark Red
	2:  hexToRGB("#FF4500"), // Red
	3:  hexToRGB("#FFA800"), // Orange
	4:  hexToRGB("#FFD635"), // Yellow
	5:  hexToRGB("#FFF8B8"), // Light Yellow
	6:  hexToRGB("#00A368"), // Dark Green
	7:  hexToRGB("#00CC78"), // Green
	8:  hexToRGB("#7EED56"), // Light Green
	9:  hexToRGB("#00756F"), // Dark Teal
	10: hexToRGB("#009EAA"), // Teal
	11: hexToRGB("#00CCC0"), // Light Teal
	12: hexToRGB("#2450A4"), // Dark Blue
	13: hexToRGB("#3690EA"), // Blue
	14: hexToRGB("#51E9F4"), // Light Blue
	15: hexToRGB("#493AC1"), // Indigo
	16: hexToRGB("#6A5CFF"), // Periwinkle
	17: hexToRGB("#94B3FF"), // Lavender
	18: hexToRGB("#811E9F"), // Dark Purple
	19: hexToRGB("#B44AC0"), // Purple
	20: hexToRGB("#E4ABFF"), // Light Purple
	21: hexToRGB("#DE107F"), // Magenta
	22: hexToRGB("#FF3881"), // Pink
	23: hexToRGB("#FF99AA"), // Light Pink
	24: hexToRGB("#6D482F"), // Dark Brown
	25: hexToRGB("#9C6926"), // Brown
	26: hexToRGB("#FFB470"), // Beige
	27: hexToRGB("#000000"), // Black
	28: hexToRGB("#515252"), // Dark Gray
	29: hexToRGB("#898D90"), // Gray
	30: hexToRGB("#D4D7D9"), // Light Gray
	31: hexToRGB("#FFFFFF"), // White
}

**Comment by Edouard127** [comment]
well that doesn't look right

**Comment by agustinmorantes** [comment]
I think I may have found the problem. 

In the closestColor function at line 154, the condition is checking if closestDistance is zero. Once the function finds an exact match, this condition will be true for the next loop, it then replaces the closest color with the next color regarding the distance, resulting in an incorrect value.

Replacing the condition at line 54 with 
```go
if distance < closestDistance {
 ```
should fix the problem.

**Comment by DrMaxNix** [comment]
I did some debugging and think I found the problem: PR #88
