### ISSUE TITLE
newbie here

### ISSUE THREAD

**Issue by tropink** [Edouard127/reddit-placebot-2023#29]
hello! can anyone give me a step by step guide on how to run this? I ran bots last year, but it was a bit more straightforward (python), i dont do coding usually so this guide being so barebones is hard for me to follow, i installed the tor thing and go, but im unsure where to go now,

**Comment by r4ngu** [comment]
Download "go" (just search "go" on Google, if the first link is "The Go Programming Language" then you're in the right place)
Download "The Tor Expert Bundle" (https://www.torproject.org/download/tor/)
Put your image (should be format .bmp instead of .png or .jpg) inside folder images
Go to data and config your accounts inside of users.json
Open a CMD inside the script's file.
Type "go build ." inside of the CMD
Wait some minutes.
If a .exe called "redditplacebot.exe" appears, then you're in the right place.
Before running redditplacebot.exe turn off your anti-virus since false positives (if it's about leakless.exe then you're fine, it's a Go plugin)
Open your CMD again, click the .exe and put it on the CMD
Type your coords after the redditplacebot.exe PATH, it might look like this: .redditplacebot.exe -minX=(Insert X coord in here) -minY=(Insert Y coord in here)

**Comment by Edouard127** [comment]
I've updated the readme

**Comment by Edouard127** [comment]
> Download "go" (just search "go" on Google, if the first link is "The Go Programming Language" then you're in the right place) Download "The Tor Expert Bundle" (https://www.torproject.org/download/tor/) and run "tor.exe" inside of folder tor (in the link you downloaded) Put your image (should be format .bmp instead of .png or .jpg) inside folder images Go to data and config your accounts inside of users.json Open a CMD inside the script's file. Type "go build ." inside of the CMD Wait some minutes. If a .exe called "redditplacebot.exe" appears, then you're in the right place. Before running redditplacebot.exe turn off your anti-virus since false positives (if it's about leakless.exe then you're fine, it's a Go plugin) Open your CMD again, click the .exe and put it on the CMD Type your coords after the redditplacebot.exe PATH, it might look like this: C:/blablabla/redditplacebot.exe -minX=(Insert X coord in here) -minY=(Insert Y coord in here)

I've disabled leakless, I just have to manually close the browser

**Comment by tropink** [comment]
> 

thank you soo! much, only thing now is to add the workers, i tried using notepad++, typing them in and then renaming it from user.json.rename to user.json (replacing the one there) but now i get panic: I could not decode the users.json file: invalid character '"' after object key

**Comment by tropink** [comment]
THANK YOU SO MUCH

> Download "go" (just search "go" on Google, if the first link is "The Go Programming Language" then you're in the right place) Download "The Tor Expert Bundle" (https://www.torproject.org/download/tor/) and run "tor.exe" inside of folder tor (in the link you downloaded) Put your image (should be format .bmp instead of .png or .jpg) inside folder images Go to data and config your accounts inside of users.json Open a CMD inside the script's file. Type "go build ." inside of the CMD Wait some minutes. If a .exe called "redditplacebot.exe" appears, then you're in the right place. Before running redditplacebot.exe turn off your anti-virus since false positives (if it's about leakless.exe then you're fine, it's a Go plugin) Open your CMD again, click the .exe and put it on the CMD Type your coords after the redditplacebot.exe PATH, it might look like this: C:/blablabla/redditplacebot.exe -minX=(Insert X coord in here) -minY=(Insert Y coord in here)

THANK YOU SO MUCH YOU THE BEST

**Comment by r4ngu** [comment]
> THANK YOU SO MUCH
> 
> > Download "go" (just search "go" on Google, if the first link is "The Go Programming Language" then you're in the right place) Download "The Tor Expert Bundle" (https://www.torproject.org/download/tor/) and run "tor.exe" inside of folder tor (in the link you downloaded) Put your image (should be format .bmp instead of .png or .jpg) inside folder images Go to data and config your accounts inside of users.json Open a CMD inside the script's file. Type "go build ." inside of the CMD Wait some minutes. If a .exe called "redditplacebot.exe" appears, then you're in the right place. Before running redditplacebot.exe turn off your anti-virus since false positives (if it's about leakless.exe then you're fine, it's a Go plugin) Open your CMD again, click the .exe and put it on the CMD Type your coords after the redditplacebot.exe PATH, it might look like this: C:/blablabla/redditplacebot.exe -minX=(Insert X coord in here) -minY=(Insert Y coord in here)
> 
> THANK YOU SO MUCH YOU THE BEST

np

**Comment by orelt06** [comment]
> Download "go" (just search "go" on Google, if the first link is "The Go Programming Language" then you're in the right place) Download "The Tor Expert Bundle" (https://www.torproject.org/download/tor/) and run "tor.exe" inside of folder tor (in the link you downloaded) Put your image (should be format .bmp instead of .png or .jpg) inside folder images Go to data and config your accounts inside of users.json Open a CMD inside the script's file. Type "go build ." inside of the CMD Wait some minutes. If a .exe called "redditplacebot.exe" appears, then you're in the right place. Before running redditplacebot.exe turn off your anti-virus since false positives (if it's about leakless.exe then you're fine, it's a Go plugin) Open your CMD again, click the .exe and put it on the CMD Type your coords after the redditplacebot.exe PATH, it might look like this: C:/blablabla/redditplacebot.exe -minX=(Insert X coord in here) -minY=(Insert Y coord in here)

what do you mean by "Open a CMD inside the script's file."? open a CMD and cd it to the directory?
