### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SilverKing3234** [Edouard127/reddit-placebot-2023#33]
I get this error when i launch the program:
main.readClients(0x3b9aca00?, 0xc0001aa870)
        C:/Users/Error/Downloads/reddit-placebot-2023-master/main.go:57 +0xe4e
main.main()
        C:/Users/Error/Downloads/reddit-placebot-2023-master/main.go:26 +0x30e
        
Can you help me? idk why i get this error, ChatGPT said what i get error because some functions don't exists

**Comment by Edouard127** [comment]
You didn't read the tutorial have you

```
	file, err := os.Open("data/users.json")
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			os.Create("data/users.json")
			panic("Please add users to the users.json file")
		}
		panic(err)
	}
	```

**Comment by SilverKing3234** [comment]
How many users do you recommend?

**Comment by Edouard127** [comment]
> How many users do you recommend?

1 user for 2 pixels
