### ISSUE TITLE
What should I do?

### ISSUE THREAD

**Issue by rodomils** [Edouard127/reddit-placebot-2023#34]
Basically, I'm trying to do it with a lot of users, but I checked them right now and they were suspended for suspicious activities, is this an IP ban or something? Idk what to do to bypass this thing on new users being added.

**Comment by Edouard127** [comment]
If on r/place the timer for the next pixel is huge, then it's a r/place ban
But If you can still place pixels on the browser, but no one else sees them, it's a shadowban
I've found this post on reddit and you get some info about what can get an account banned for suspicious activities
https://www.reddit.com/r/RedditEng/comments/wro64p/how_we_built_rplace_2022_bots_and_safety/
