### ISSUE TITLE
QUESTION: How exactly do I use tor? 

### ISSUE THREAD

**Issue by urkoperez16** [Edouard127/reddit-placebot-2023#35]
I have never used it before and even less in the expert bundle option.

**Comment by Edouard127** [comment]
Not getting your accounts banned

**Comment by urkoperez16** [comment]
> Not getting your accounts banned

but how, i never use it

**Comment by Edouard127** [comment]
Read the tutorial

**Comment by Edouard127** [comment]
> > Read the tutorial
> 
> Oh, i didnt see it, last question, which .exe i need to put in system variable

You should put the entire folder
