### ISSUE TITLE
 websocket.Dial Problem

### ISSUE THREAD

**Issue by cereal-kitty** [Edouard127/reddit-placebot-2023#36]
i'm not sure yet but i tried the latest version it gave me something like this : 
panic: websocket.Dial wss://gql-realtime-2.reddit.com/query: EOF

**Comment by Edouard127** [comment]
Give me the full error stack

**Comment by cereal-kitty** [comment]
panic: websocket.Dial wss://gql-realtime-2.reddit.com/query: EOF

goroutine 1 [running]:
main.readClients(0x3b9aca00?, 0xc000380060)
        D:/Desktop2/try-/main.go:112 +0xdc7
main.main()
        D:/Desktop2/try-/main.go:28 +0x365

Process finished with the exit code 2

**Comment by Edouard127** [comment]
There's something wrong with your dialer
Is the tor node running with no issues ?

**Comment by cereal-kitty** [comment]
oh sry i think i understood. But it comes back :
Waiting for login to finish...
Error receiving message from socket EOF
2023-07-23T09:58:47.866+0800    INFO    try-/client.go:81       Login successful                                                                                                   {
"username": "Klutzy-Put-6652"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0xfd22a3]

goroutine 32 [running]:
main.listenForCircuit(0x0?, 0xc0003a1f68?)
        D:/Desktop2/try-/util.go:81 +0xe3
created by main.(*Client).Setup
        D:/Desktop2/try-/client.go:245 +0x396

Process finished with the exit code 2

**Comment by Edouard127** [comment]
#30

**Comment by Edouard127** [comment]
Can you try using the latest commit ?
You will get the error message so I can debug it faster

**Comment by cereal-kitty** [comment]
emm sure. i believe it was a proxy problem and the latest in commit is the problem [#30](https://github.com/Edouard127/reddit-placebot-2023/issues/30)
