### ISSUE TITLE
How the /appdata/tor .txt or .bat file should end up?

### ISSUE THREAD

**Issue by urkoperez16** [Edouard127/reddit-placebot-2023#38]

**Comment by Edouard127** [comment]
what

**Comment by urkoperez16** [comment]
> what

Put this in a file named torrc on Windows at %APPDATA%\tor\

 how end uo this file

**Comment by Edouard127** [comment]
The filename is torrc, there's no extension

**Comment by urkoperez16** [comment]
> The filename is torrc, there's no extension

ooh, thanks for replying these absurd but necessary questions for me
