### ISSUE TITLE
stuck at waiting for login to finish

### ISSUE THREAD

**Issue by tropink** [Edouard127/reddit-placebot-2023#39]
Waiting for login to finish...
2023-07-22T22:23:37.506-0400    INFO    reddit-placebot-2023-master/client.go:81        Login successful        {"username": "EnvironmentalLet1241"}
2023-07-22T22:23:37.602-0400    INFO    reddit-placebot-2023-master/board.go:50 Controller changed      {"username": "EnvironmentalLet1241"}

am i doing something wrong?

**Comment by Edouard127** [comment]
You only have one account ?

**Comment by tropink** [comment]
I put two to try it out, but it doesn't go past the first one

**Comment by Edouard127** [comment]
> I put two to try it out, but it doesn't go past the first one

Try to remove the account that causes issues

**Comment by rodomils** [comment]
my case is the same, but instead of two accounts, i have 100+, is there any way to detect the ones that are causing the issues?
all of them are valid, but some are suspended from reddit.

**Comment by rodomils** [comment]
![image](https://github.com/Edouard127/reddit-placebot-2023/assets/117560269/5f31849f-75a7-4b8a-8bee-fd7d0d4a21d4)
also this happens when i put more than 3~ accounts, any fixes?

**Comment by Edouard127** [comment]
The error does cause any issues, you just have to restart after

**Comment by rodomils** [comment]
ok, so I must wait till it finishes getting info from all accounts then run again right?

**Comment by Edouard127** [comment]
yes

**Comment by tropink** [comment]
I tried with a fresh account and it still not going past that, I restarted and it goes back to waiting for login to finish

**Comment by rodomils** [comment]
the thing is, it freezes at some point and idk which account is causing the issue
![image](https://github.com/Edouard127/reddit-placebot-2023/assets/117560269/2cda1cd5-ee15-4182-8e22-04cc4d1505b4)
as you can see, the last one was at 23:40 (11:40 PM) and now 4 minutes have passed and nothing changed.

**Comment by Edouard127** [comment]
exit and restart

**Comment by rodomils** [comment]
alr will do that but why would this work

**Comment by rodomils** [comment]
also im sorry for this moment of "overcharge" as i see that a lot of people are having issues, but you are helping everyone and giving your best, thank you for doing that, you deserve good things, keep helping people.

**Comment by tropink** [comment]
I let it run for a little bit longer, and i got this at the end Error receiving message from socket EOF

**Comment by Edouard127** [comment]
It's reddit kicking you out of the socket because you're not doing anything

**Comment by rodomils** [comment]
i figured it out, if you use more than 3 alt accounts in the same IP, reddit will "suspend" your alt accounts for suspicious reasons, i think that we need proxies for that, but its hard to add them.

**Comment by LeSunset** [comment]
Please remove tor for proxy and just add a normal proxylist @Edouard127
