### ISSUE TITLE
I don't get it

### ISSUE THREAD

**Issue by ZyleakReal** [Edouard127/reddit-placebot-2023#41]
Can u do like an tutorial video i don't know what to do,im reading the readme.md but still don't know what to do?

**Comment by rodomils** [comment]
I can help you, which part are you stuck in?

**Comment by ZyleakReal** [comment]
im stuck . on the first part XD

**Comment by rodomils** [comment]
Ok, so first of all, download the .zip file on github, 
![image](https://github.com/Edouard127/reddit-placebot-2023/assets/117560269/91873c43-844c-4aa9-8d4b-d9aafaf11ce0)
Click on the green button, "Code"
Then download as ZIP and extract somewhere in your computer.
Next download the tor bundle: https://archive.torproject.org/tor-package-archive/torbrowser/12.5.1/tor-expert-bundle-12.5.1-windows-x86_64.tar.gz

**Comment by rodomils** [comment]
Then try to follow this: https://github.com/Edouard127/reddit-placebot-2023#how-to-use
Lmk if you have any problems

**Comment by ZyleakReal** [comment]
thx :)

**Comment by warior456** [comment]
> Ok, so first of all, download the .zip file on github, ![image](https://user-images.githubusercontent.com/117560269/255372303-91873c43-844c-4aa9-8d4b-d9aafaf11ce0.png) Click on the green button, "Code" Then download as ZIP and extract somewhere in your computer. Next download the tor bundle: https://archive.torproject.org/tor-package-archive/torbrowser/12.5.1/tor-expert-bundle-12.5.1-windows-x86_64.tar.gz

what do i do when i download the expert bundle?

**Comment by Obelisx** [comment]
> > Ok, so first of all, download the .zip file on github, ![image](https://user-images.githubusercontent.com/117560269/255372303-91873c43-844c-4aa9-8d4b-d9aafaf11ce0.png) Click on the green button, "Code" Then download as ZIP and extract somewhere in your computer. Next download the tor bundle: https://archive.torproject.org/tor-package-archive/torbrowser/12.5.1/tor-expert-bundle-12.5.1-windows-x86_64.tar.gz
> 
> what do i do when i download the expert bundle? just downloading it wont do anything since it's not installed or anything

Sorry for being late, but you just have to open the tor.exe after following the path tutorial. tor.exe will open a terminal, make sure it bootstraps 100%.
