### ISSUE TITLE
message": "Pixel was not placed, or was placed somewhere else"

### ISSUE THREAD

**Issue by jacekwitko98** [Edouard127/reddit-placebot-2023#42]
example of whats happening 
"2023-07-23T05:36:22.840+0200    INFO    reddit-placebot-2023-master/client.go:308       There was an error placing pixel        {"username": "nugusMadelei66664", "message": "Pixel was not placed, or was placed somewhere else"}
2023-07-23T05:36:22.840+0200    INFO    reddit-placebot-2023-master/worker.go:49        Placing client  {"username": "nugusEmmiPik47179"}"

**Comment by cereal-kitty** [comment]
https://github.com/Edouard127/reddit-placebot-2023/issues/24
