### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kroW-Urven** [Edouard127/reddit-placebot-2023#44]
> > Waiting for login to finish... Get "https://api.ipify.org?format=json": socks connect tcp 127.0.0.1:9050->api.ipify.org:443: dial tcp 127.0.0.1:9050: connectex: No connection could be made because the target mac hine actively refused it. panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x24 pc=0x4a8e24] goroutine 40 [running]: main.listenForCircuit(0x2540be400, 0xa2864a0) D:/Desktop2/reddit-placebot-2023-master/util.go:89 +0x1c4 created by main.main D:/Desktop2/reddit-placebot-2023-master/main.go:61 +0x6cd Process finished with the exit code 2
> 
> Alright so I've changed the api, try again If It doesn't work I don't know what else to do

Getting the same issue

Get "https://api.seeip.org/jsonip": socks connect tcp 127.0.0.1:9050->api.seeip.org:443: dial tcp 127.0.0.1:9050: connectex: No connection could be made because the target machine actively refused it.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x24 pc=0x8d8db7]

goroutine 180 [running]:
main.listenForCircuit(0x2540be400, 0xa894100)
        C:/Desktop/util.go:89 +0x1c7
created by main.(*Client).Setup
        C:/Desktop/client.go:245 +0x363

**Comment by cereal-kitty** [comment]
emmm... we tried to solve the problem for hours, you can check https://github.com/Edouard127/reddit-placebot-2023/issues/30 to check out if there are some useful information.

**Comment by cereal-kitty** [comment]
i think i find out the problem. let me make sure : are you using a VPN ?
