### ISSUE TITLE
How do i start the program 

### ISSUE THREAD

**Issue by Silasllla** [Edouard127/reddit-placebot-2023#45]
What do I have to write

**Comment by urkoperez16** [comment]
When you finish the tutorial in Windows you can use PowerShell and if you haven't finished it, you can finish it in PowerShell.

**Comment by Silasllla** [comment]
I know but when i write this ./ri ./redditplacebot -minX=64 -minY=64 it says it dosent exist

**Comment by Edouard127** [comment]
Read the tutorial

**Comment by Silasllla** [comment]
I've read the tutorial but when I type ./redditplacebot -minX=64 -minY=64 it comes up
'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Obelisx** [comment]
> I've read the tutorial but when I type ./redditplacebot -minX=64 -minY=64 it comes up '.' is not recognized as an internal or external command, operable program or batch file.

On Windows, you can shift+right click a folder and select 'open PowerShell window here'. It will then recognize the internal commands. Alternatively, drag the .exe into terminal and at the end write the -minX & -minY
