### ISSUE TITLE
Way less pixels getting place than accounts exist

### ISSUE THREAD

**Issue by LeSunset** [Edouard127/reddit-placebot-2023#46]
Hey,

beside the issue that the wrong colors get placed, I also have the following problem.
I have like 60+ Accounts but from these 60+ Accounts not even 10 pixels get placed in a run.

Most of the accounts are getting this error: "Pixel was not placed, or was placed somewhere else"

How to fix it?

**Comment by cereal-kitty** [comment]
https://github.com/Edouard127/reddit-placebot-2023/issues/24
