### ISSUE TITLE
The program says that denegated my connection

### ISSUE THREAD

**Issue by urkoperez16** [Edouard127/reddit-placebot-2023#47]
It put the same but in Spanish:

Get "https://api.seeip.org/jsonip": socks connect tcp 127.0.0.1:9050->api.seeip.org:443: dial tcp 127.0.0.1:9050: connectex: **No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.**
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0xf222b9]

**Comment by cereal-kitty** [comment]
seems that we all have the same problem...

**Comment by Edouard127** [comment]
#30
