### ISSUE TITLE
API Connection Actively Refused

### ISSUE THREAD

**Issue by RoboPenguin7** [Edouard127/reddit-placebot-2023#50]
Get "https://api.seeip.org/jsonip": socks connect tcp 127.0.0.1:9050->api.seeip.org:443: dial tcp 127.0.0.1:9050: connectex: No connection could be made because the target machine actively refused it.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0xf622b9]

**Comment by Shazz303** [comment]
same here

**Comment by HeyMika** [comment]
Seems to be an issue with seeip.org and not the program itself.

**Comment by yahyaalx** [comment]
panic: websocket.Dial wss://gql-realtime-2.reddit.com/query: dial tcp: lookup gql-realtime-2.reddit.com on 172: socks connect udp 127->172: network not implemented

**Comment by HeyMika** [comment]
Okay never mind it seems it's not an issue with seeip.org. I tried ipify.org and it doesn't work as well.

**Comment by Edouard127** [comment]
#30
