### ISSUE TITLE
Error receiving message from socket EOF

### ISSUE THREAD

**Issue by Shazz303** [Edouard127/reddit-placebot-2023#51]
some kind of error while running the bot, i think it's api related

**Comment by Edouard127** [comment]
Just restart the program after login into a lot of accounts

**Comment by Shazz303** [comment]
2023-07-23T19:54:33.779+0600    INFO    reddit-placebot-2023-master/client.go:82        Login successful        {"username": "*******"}
Error receiving message from socket EOF

**Comment by Shazz303** [comment]
still getting it
