### ISSUE TITLE
It does nothing

### ISSUE THREAD

**Issue by TomiLikesToCode** [Edouard127/reddit-placebot-2023#55]
main.readClients(0x3b9aca00?, 0xc0002a48a0)
        D:/a/reddit-placebot-2023/reddit-placebot-2023/main.go:61 +0xebe
main.main()
        D:/a/reddit-placebot-2023/reddit-placebot-2023/main.go:28 +0x365

this is the only message i get and no pixels are placed

**Comment by r4ngu** [comment]
did you build it or smth?

**Comment by TomiLikesToCode** [comment]
No
