### ISSUE TITLE
cant launch with powershell

### ISSUE THREAD

**Issue by jackoridd7** [Edouard127/reddit-placebot-2023#56]
when launching in the reddit-placebot-2023-master folder i get the error code:

./redditplacebot : The term './redditplacebot' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ ./redditplacebot -minX=64 -minY=64
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./redditplacebot:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by r4ngu** [comment]
drag redditplacebot.exe (if you builded the program) to your terminal hen type your coords where you want your pixel art to be at (-minX=-minY=)

**Comment by jackoridd7** [comment]
i didnt build the program do i do that on windows? sorry im a total noob at this stuff lol

**Comment by r4ngu** [comment]
oops sorry for late response, go to "how-to-build" section in the readme, yes you can do it on windows

**Comment by jackoridd7** [comment]
thankyou for the fast response ;)

**Comment by jackoridd7** [comment]
do i put:
go build .

into powershell?

**Comment by r4ngu** [comment]
yes

**Comment by jackoridd7** [comment]
go : The term 'go' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ go build .
+ ~~
    + CategoryInfo          : ObjectNotFound: (go:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by r4ngu** [comment]
download go

**Comment by jackoridd7** [comment]
hmm i have already

**Comment by jackoridd7** [comment]
i restarted and seems to be working now thanks

**Comment by jackoridd7** [comment]
panic: I could not decode the users.json file: invalid character 'j' after object key

goroutine 1 [running]:
main.readClients(0x3b9aca00?, 0xc00017a240)
        C:/Users/jacko/Downloads/reddit-placebot-2023-master/reddit-placebot-2023-master/main.go:71 +0xe3f
main.main()
        C:/Users/jacko/Downloads/reddit-placebot-2023-master/reddit-placebot-2023-master/main.go:28 +0x365
PS C:\Users\jacko\Downloads\reddit-placebot-2023-master\reddit-placebot-2023-master>

**Comment by jackoridd7** [comment]
[{"username": "jackoridd2", "password": "password"}, {"username: "jackoridd3", "password": "password"}, {"username: "jackoridd7", "password": "password"}, {"username: "sazzacazza", "password": "password"}, {"username: "cazzasazza", "password": "password"}]

**Comment by r4ngu** [comment]
looks like users.json is not completed, a quote (") is missing after "username", fix it like this

[{"username**_"_**: "example", "password": "example"}, {"username**_"_**: "example", "password": "password"}]

not this

[{"username: "example", "password": "example"}, {"username: "example", "password": "password"}]

**Comment by r4ngu** [comment]
srry for late response again

**Comment by urkoperez16** [comment]
the ** are necessary?

**Comment by r4ngu** [comment]
nope, it was a mistake of mine when using bold text for my example

**Comment by urkoperez16** [comment]
aah ok, thanks
