### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jauga** [Edouard127/reddit-placebot-2023#6]
Got an error trying to connect.

`Error sending request   {"username": "UserName", "error": "Post \"https://gql-realtime-2.reddit.com/query\": socks connect tcp 127.0.0.1:9050->gql-realtime-2.reddit.com:443: dial tcp 127.0.0.1:9050: connectex: No connection could be made because the target machine actively refused it."}`

**Comment by Edouard127** [comment]
You need to run a tor node locally, read the tutorial

**Comment by Jauga** [comment]
`SocksPort 9050` in torrc file solved the issue.
