### ISSUE TITLE
network not implemented

### ISSUE THREAD

**Issue by SuperPou1** [Edouard127/reddit-placebot-2023#60]
i get this error:
```
panic: websocket.Dial wss://gql-realtime-2.reddit.com/query: dial tcp: lookup gql-realtime-2.reddit.com on 127.0.0.53:53: socks connect udp 127.0.0.1:9050->127.0.0.53:53: network not implemented

goroutine 1 [running]:
main.readClients(0x3b9aca00?, 0xc0001d4570)
	/home/runner/work/reddit-placebot-2023/reddit-placebot-2023/main.go:112 +0xdc7
main.main()
	/home/runner/work/reddit-placebot-2023/reddit-placebot-2023/main.go:28 +0x365
```
i'm using ubuntu 22.04. how do i fix this?

**Comment by r4ngu** [comment]
if im not wrong, run tor.exe inside of the tor expert bundle file, btw, dont forget to build the program

**Comment by SuperPou1** [comment]
first of all, i'm using linux, so i need to use the linux executable, second of all, i just downloaded it from artifacts so i don't need to build it, unless u say that i need to build it myself

**Comment by Saiv46** [comment]
I builted that, also tried to replace DNS server with `1.1.1.1`

Same result
```
panic: websocket.Dial wss://gql-realtime-2.reddit.com/query: dial tcp: lookup gql-realtime-2.reddit.com on 127.0.0.53:53: socks connect udp 127.0.0.1:9050->1.1.1.1:53: network not implemented

goroutine 1 [running]:
main.readClients(0x3b9aca00?, 0xc00007e540)
	/home/saiv46/reddit-placebot-2023/main.go:112 +0xdc7
main.main()
	/home/saiv46/reddit-placebot-2023/main.go:28 +0x365
```

**Comment by Saiv46** [comment]
Apparently SOCKS doesn't support UDP: golang/go#32790

**Comment by Saiv46** [comment]
@SuperPou1 @GionotranteBolotroloco As temporary solution you can edit source code and build

For example
```diff
index e234aa7..ecccb3d 100644
--- a/main.go
+++ b/main.go
@@ -95,7 +95,7 @@ func readClients(logger *zap.Logger, browser *Browser) (clients []*Client) {
        config.Dialer = &net.Dialer{
                Resolver: &net.Resolver{
                        Dial: func(ctx context.Context, network, address string) (net.Conn, error) {
-                               return dialer.Dial(network, address)
+                               return dialer.Dial("tcp", "1.1.1.1:53")
                        },
                },
        }

```

**Comment by GionotranteBolotroloco** [comment]
> @SuperPou1 @GionotranteBolotroloco As temporary solution you can edit source code and build
> 
> For example
> 
> ```diff
> index e234aa7..ecccb3d 100644
> --- a/main.go
> +++ b/main.go
> @@ -95,7 +95,7 @@ func readClients(logger *zap.Logger, browser *Browser) (clients []*Client) {
>         config.Dialer = &net.Dialer{
>                 Resolver: &net.Resolver{
>                         Dial: func(ctx context.Context, network, address string) (net.Conn, error) {
> -                               return dialer.Dial(network, address)
> +                               return dialer.Dial("tcp", "1.1.1.1:53")
>                         },
>                 },
>         }
> ```

it worked thanks

**Comment by SuperPou1** [comment]
well, now i got 
```
panic: websocket.Dial wss://gql-realtime-2.reddit.com/query: dial tcp: lookup gql-realtime-2.reddit.com on 127.0.0.53:53: socks connect tcp 127.0.0.1:9050->1.1.1.1:53: dial tcp 127.0.0.1:9050: connect: connection refused
```

**Comment by SuperPou1** [comment]
worked for me too… now wait for another update to fix the board loading issue
