### ISSUE TITLE
where is the torrc file?

### ISSUE THREAD

**Issue by orelt06** [Edouard127/reddit-placebot-2023#63]
in [this link](https://github.com/Edouard127/reddit-placebot-2023#how-to-avoid-getting-banned) it has been said that to avoid getting banned we need to put 
`CircuitBuildTimeout 30
LearnCircuitBuildTimeout 0 
MaxCircuitDirtiness 30`
in a file named "torrc" at: %APPDATA%\tor\
i cant find that file...
do i need to create it myself?

**Comment by r4ngu** [comment]
yes...

**Comment by orelt06** [comment]
![image](https://github.com/Edouard127/reddit-placebot-2023/assets/78733606/2b5922d3-9aff-4e75-bd9d-56bf90aa9cc7)
create it here?

**Comment by r4ngu** [comment]
yea
