### ISSUE TITLE
my leakless.exe accidently got deleted by my anti virus

### ISSUE THREAD

**Issue by orelt06** [Edouard127/reddit-placebot-2023#65]
i started running the log in and it said that one user was succesful and then my anti virus quarantined leakless.exe . I tried to restore it but it didnt come back and now im not sure what to do. it currently gets stuck at "Waiting for login to finish..."

is there any way that i can redownload leakless?

**Comment by darkmaster420** [comment]
It does it by itself. You can just turn off your antivirus and run it again
