### ISSUE TITLE
Stuck at waiting for board data

### ISSUE THREAD

**Issue by darkmaster420** [Edouard127/reddit-placebot-2023#66]
![Screenshot_20230723-112015](https://github.com/Edouard127/reddit-placebot-2023/assets/64340223/e1c12f5c-5b57-442c-9061-d3b7d01dbd72)
Launched Tor and login was successful. Am I missing something?

**Comment by BrunoZockt** [comment]
Same error. I think it happens because the canvas has expanded and the program can't handle it. Couldn't fix it yet though.

**Comment by r4ngu** [comment]
yeah, wait for Edouard127 to update the code

**Comment by r4ngu** [comment]
go to board.go and modify the values it might work

**Comment by orelt06** [comment]
@Edouard127 please fix!

**Comment by n1ebe** [comment]
same error, "waiting for board data"

**Comment by asdhuman-dev** [comment]
same error, @Edouard127, fix please <3

**Comment by Edouard127** [comment]
1521c71
