### ISSUE TITLE
why do i get this error?

### ISSUE THREAD

**Issue by orelt06** [Edouard127/reddit-placebot-2023#67]
when i try to run it it says login succesful and then `Get "https://api.seeip.org/jsonip": socks connect tcp 127.0.0.1:9050->api.seeip.org:443: dial tcp 127.0.0.1:9050: connectex: No connection could be made because the target machine actively refused it.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0xa122b9]`

**Comment by n1ebe** [comment]
same error

**Comment by r4ngu** [comment]
remember to run tor.exe doing that fixes it

**Comment by orelt06** [comment]
still not fixed... could it error because of torrc? its path is "C:\Users\user\AppData\Roaming\tor\torrc" meanwhile the tor.exe path is: "D:\rplace\1\TOR\tor\tor.exe"

**Comment by n1ebe** [comment]
run tor and it fixes the problem, thanks guys

**Comment by orelt06** [comment]
now when i run tor.exe in the CMD it responds with this:
`[warn] Failed to parse/validate config: Could not parse CircuitBuildTimeout: Provided value is malformed or out of bounds: Unknown unit in 30 LearnCircuitBuildTimeout 0  MaxCircuitDirtiness 30

[err] Reading config failed--see warnings above.`

**Comment by orelt06** [comment]
nevermind i fixed it, just needed to sort the data in torrc, thank you so much for the help
