### ISSUE TITLE
Waiting for board data

### ISSUE THREAD

**Issue by Gamer6MD** [Edouard127/reddit-placebot-2023#69]
The script stayed like that for a few minutes. Any thoughts?

E:\!RPlace Bots\reddit-placebot-2023-master>redditplacebot -minX=-643 -minY=-425
Waiting for login to finish...
2023-07-23T22:26:38.181+0300    ERROR   reddit-placebot-2023-master/client.go:66        Login failed    {"username": "", "username": ""}
main.(*Client).Login
        E:/!RPlace Bots/reddit-placebot-2023-master/client.go:66
main.main.func1
        E:/!RPlace Bots/reddit-placebot-2023-master/main.go:35
2023-07-23T22:26:42.416+0300    ERROR   reddit-placebot-2023-master/client.go:66        Login failed    {"username": "", "username": ""}
main.(*Client).Login
        E:/!RPlace Bots/reddit-placebot-2023-master/client.go:66
main.main.func1
        E:/!RPlace Bots/reddit-placebot-2023-master/main.go:35
Login finished!
Waiting for board data

**Comment by LucasMucaz** [comment]
canvas expanded . wait for edouard to fix it

**Comment by r4ngu** [comment]
Dupe #66 #68

**Comment by LucasMucaz** [comment]
also you need to provide an account to login to
set the username and password in the data folder inside of the users.json text file
make sure also that you have tor.exe running at the same time

**Comment by Gamer6MD** [comment]
> also you need to provide an account to login to set the username and password in the data folder inside of the users.json text file make sure also that you have tor.exe running at the same time

I added accounts this way but I get this. is it because the script is not updated or am I doing something wrong?

[{"username": "jorek61502", "password": "*********"}, {"username": "noyave5862", "password": "*********"}]

I wrote "*********" to avoid writing the actual password
Error:

2023-07-24T00:19:40.094+0300    ERROR   reddit-placebot-2023-master/client.go:66        Login failed    {"username": "jorek61502", "username": "jorek61502"}
main.(*Client).Login
        E:/!RPlace Bots/reddit-placebot-2023-master/client.go:66
main.main.func1
        E:/!RPlace Bots/reddit-placebot-2023-master/main.go:35
2023-07-24T00:19:44.361+0300    ERROR   reddit-placebot-2023-master/client.go:66        Login failed    {"username": "noyave5862", "username": "noyave5862"}
main.(*Client).Login
        E:/!RPlace Bots/reddit-placebot-2023-master/client.go:66
main.main.func1
        E:/!RPlace Bots/reddit-placebot-2023-master/main.go:35

**Comment by LucasMucaz** [comment]
the only thing i can think of is that your second account info is wrong.

**Comment by LucasMucaz** [comment]
just so you know if your account username or password has capital letters for some reason this script has problems. so keep that in mind. the creator of this script needs to fix this stuff

**Comment by yahyaalx** [comment]
panic: websocket.Dial wss://gql-realtime-2.reddit.com/query: dial tcp: lookup gql-realtime-2.reddit.com on 1.0.0.1: socks connect udp 127.0.0.1:9050->1.0.0.1:53: network not implemented

goroutine 1 [running]:
main.readClients(0x3b9aca00?, 0xc000024510)
        /home/wifi/Desktop/reddit-placebot-2023/main.go:112 +0xdc7
main.main()
        /home/wifi/Desktop/reddit-placebot-2023/main.go:28 +0x365


keeep getting this error already executed the tor.exe in the background

**Comment by Gamer6MD** [comment]
it's my fault, the login details are wrong

**Comment by LucasMucaz** [comment]
> panic: websocket.Dial wss://gql-realtime-2.reddit.com/query: dial tcp: lookup gql-realtime-2.reddit.com on 1.0.0.1: socks connect udp 127.0.0.1:9050->1.0.0.1:53: network not implemented
> 
> goroutine 1 [running]: main.readClients(0x3b9aca00?, 0xc000024510) /home/wifi/Desktop/reddit-placebot-2023/main.go:112 +0xdc7 main.main() /home/wifi/Desktop/reddit-placebot-2023/main.go:28 +0x365
> 
> keeep getting this error already executed the tor.exe in the background

have you added tor.exe to path?

**Comment by yahyaalx** [comment]
>no how to do that ??

**Comment by yahyaalx** [comment]
> 

no it s not mentioned in the readme.md!! how to do that ??

**Comment by r4ngu** [comment]
https://phoenixnap.com/kb/linux-add-to-path

**Comment by SuperPou1** [comment]
shouldn't this be a quick update to board.go?

**Comment by orelt06** [comment]
> shouldn't this be a quick update to board.go?

Do you know the fix?

**Comment by SuperPou1** [comment]
i'm trying stuff but no luck lol

**Comment by orelt06** [comment]
@Edouard127 please fix!

**Comment by Edouard127** [comment]
1521c71
