### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by GionotranteBolotroloco** [Edouard127/reddit-placebot-2023#7]
i get this error when i start the program

```
panic: websocket.Dial wss://gql-realtime-2.reddit.com/query: dial tcp: lookup gql-realtime-2.reddit.com on 127.0.0.53:53: socks connect udp 127.0.0.1:9050->127.0.0.53:53: network not implemented

goroutine 1 [running]:
main.readClients(0x3b9aca00?, 0xc0001ac8d0)
	/home/mamtfasc/Desktop/reddit-placebot-2023-master/main.go:102 +0xde7
main.main()
	/home/mamtfasc/Desktop/reddit-placebot-2023-master/main.go:26 +0x30e
```

i'm running ubuntu 22.04 and i have tor working

**Comment by Edouard127** [comment]
Try this
`sudo nano /etc/tor/torrc`

Use DNSPort 53 setting in torrc and configure nameserver to 127.0.0.1

**Comment by PacketAuditor** [comment]
What would the Torrc config file look like on Windows? I am getting the same error.

**Comment by Edouard127** [comment]
> What would the Torrc config file look like on Windows? I am getting the same error.

Create a file named torcc at the Tor/ directory

**Comment by PacketAuditor** [comment]
![image](https://github.com/Edouard127/reddit-placebot-2023/assets/140283647/6826f85c-a045-4519-85f6-842f4c355dc5)

**Comment by Edouard127** [comment]
> ![image](https://user-images.githubusercontent.com/140283647/255353396-6826f85c-a045-4519-85f6-842f4c355dc5.png)
> 
> Here is my config and it is still giving the error.

The error is unrelated, there's no accounts

**Comment by PacketAuditor** [comment]
Found it. There is missing quotation mark in users.json.rename.

**Comment by GionotranteBolotroloco** [comment]
> Try this `sudo nano /etc/tor/torrc`
> 
> Use DNSPort 53 setting in torrc and configure nameserver to 127.0.0.1

 i tried it but it still doesn't work

**Comment by Edouard127** [comment]
> > Try this `sudo nano /etc/tor/torrc`
> > Use DNSPort 53 setting in torrc and configure nameserver to 127.0.0.1
> 
> i tried it but it still doesn't work

Try with nameserver to 127.0.0.53 instead

**Comment by GionotranteBolotroloco** [comment]
> > > Try this `sudo nano /etc/tor/torrc`
> > > Use DNSPort 53 setting in torrc and configure nameserver to 127.0.0.1
> > 
> > 
> > i tried it but it still doesn't work
> 
> Try with nameserver to 127.0.0.53 instead

still the same

**Comment by Edouard127** [comment]
![image](https://github.com/Edouard127/reddit-placebot-2023/assets/46357922/291653e8-e8e2-4737-a703-8bfae548ba16)

**Comment by GionotranteBolotroloco** [comment]
> ![image](https://user-images.githubusercontent.com/46357922/255353645-291653e8-e8e2-4737-a703-8bfae548ba16.png)

that's not mine, i'm not getting any errors from tor

**Comment by Edouard127** [comment]
@GionotranteBolotroloco My bad, the config file must be in %APPDATA%/tor/

**Comment by GionotranteBolotroloco** [comment]
> @GionotranteBolotroloco My bad, the config file must be in %APPDATA%/tor/

i'm on linux so it's in /etc/tor/torrc but even after adding the things you said it still isn't working

**Comment by SuperPou1** [comment]
i have the same issue, i'm on the same version of ubuntu, can somebody explain what should i do?

**Comment by Obelisx** [comment]
I'm having launch problems also. It keeps showing a login error, but I'm sure the file is filled in when I save it. Then after running this error and opening it, it's empty showing only `[]`. I don't know what to do.

`PS C:\Users\X\OneDrive\Desktop\reddit-placebot-2023-master> ./redditplacebot -minX=1134 -minY=337
Waiting for login to finish...
2023-07-25T00:30:26.127+0200    ERROR   reddit-placebot-2023-master/client.go:69        Login failed    {"username": "", "username": ""}
main.(*Client).Login
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/client.go:69
main.main.func1
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/main.go:33
2023-07-25T00:30:30.618+0200    ERROR   reddit-placebot-2023-master/client.go:69        Login failed    {"username": "", "username": ""}
main.(*Client).Login
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/client.go:69
main.main.func1
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/main.go:33
Login finished!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x50a3cf]

goroutine 1 [running]:
main.(*Board).GetDifferentData(0xa44b020)
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/board.go:43 +0x7f
main.(*Worker).Run(0xa425d00)
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/worker.go:37 +0x4e
main.main()
        C:/Users/X/OneDrive/Desktop/reddit-placebot-2023-master/main.go:47 +0x5b8`
