### ISSUE TITLE
Add an image to images/image.bmp

### ISSUE THREAD

**Issue by mehulpuri** [Edouard127/reddit-placebot-2023#73]
There is already an image inside images/image.bmp but this error shows up

Waiting for login to finish...
2023-07-24T11:09:42.367+0530    INFO    reddit-placebot-2023-master/client.go:84        Login successful        {"username": "tyuan432"}
2023-07-24T11:09:43.976+0530    INFO    reddit-placebot-2023-master/board.go:50 Controller changed
        {"username": "tyuan432"}
panic: Please add an image to the images/image.bmp file

goroutine 72 [running]:
main.LoadBMP(0x38, 0x3d1)
        C:/Users/lonew/Desktop/reddit-placebot-2023-master/bmp.go:69 +0x2c8
main.(*Client).connect(0xc00031ac60, 0xc000340100)
        C:/Users/lonew/Desktop/reddit-placebot-2023-master/client.go:193 +0x905
created by main.(*Client).Login
        C:/Users/lonew/Desktop/reddit-placebot-2023-master/client.go:82 +0x62a

**Comment by mehulpuri** [comment]
Changed the image name from image.bmp to image as the filetype was already bmp

there is another error now

$ ./redditplacebot.exe -minX=56 -minY=977
Waiting for login to finish...
2023-07-24T11:20:59.827+0530    INFO    reddit-placebot-2023-master/client.go:84        Login successful        {"username": "ryan212123"}
2023-07-24T11:21:03.078+0530    INFO    reddit-placebot-2023-master/board.go:50 Controller changed
        {"username": "ryan212123"}
panic: bmp: invalid format: invalid RLE data

goroutine 45 [running]:
main.LoadBMP(0x38, 0x3d1)
        C:/Users/lonew/Desktop/reddit-placebot-2023-master/bmp.go:76 +0x265
main.(*Client).connect(0xc00028e120, 0xc0002a6100)
        C:/Users/lonew/Desktop/reddit-placebot-2023-master/client.go:193 +0x905
created by main.(*Client).Login
        C:/Users/lonew/Desktop/reddit-placebot-2023-master/client.go:82 +0x62a

**Comment by mehulpuri** [comment]
Added a random sample bpm 600X700 seems to be giving no error
![image](https://github.com/Edouard127/reddit-placebot-2023/assets/76563079/b640475c-d267-426d-bc12-07a994e75cb9)

But now nothing happens on the board

**Comment by GilDev** [comment]
Try to export/save your BMP image with another software, maybe Paint?

Paint and Graphic Converter worked for me, though I’m having wrong color issues (#28).

**Comment by Edouard127** [comment]
eedb9fc
