### ISSUE TITLE
Reddit Coordinate changing Logic got changed. 

### ISSUE THREAD

**Issue by Ritace** [Edouard127/reddit-placebot-2023#75]
In my case point to be plotted is {723 -233}. In the web 
{
  "coordinate": {
    "x": 213,
    "y": 732
  },
  "colorIndex": 31,
  "canvasIndex": 2
}
This is the coordinates that is generated. The colorIndex and canvasIndex are fine.The problem is with the "coordinate" section or in toPlacePoint  part of the code in bmp.go. 

In case of canvasIndex = 2. The code is: 
	case 2:
		x = p.X + 1500
		y = p.Y
So, there is no way x =213 is going to be generated here. The code was working fine a few hours ago. 

Only 1 case has come to mind: 
1. Reddit changed the logic. 

Am i right or something else is wrong?

**Comment by Edouard127** [comment]
eedb9fc
