### ISSUE TITLE
how to create a big amount of accounts? (that dont get banned when you run the program)

### ISSUE THREAD

**Issue by orelt06** [Edouard127/reddit-placebot-2023#77]
uuummm when i finnaly able to run the program it says that the accounts from that web are getting banned from r/place... 

the web that im using to create accounts that get banned: https://redditthrowaway.xyz/

do you have any alternatives?

**Comment by orelt06** [comment]
![image](https://github.com/Edouard127/reddit-placebot-2023/assets/78733606/e466a919-6dab-4949-9036-d51f7d9c718d)

**Comment by cereal-kitty** [comment]
join some random subs and verify the email

**Comment by orelt06** [comment]
can you be more specific?

**Comment by GilDev** [comment]
For each of your bot accounts, try to make it look like they’re genuine and not bots:
1. Login
2. Verify their email addresses
3. Join different subreddits

**Comment by orelt06** [comment]
where do i get for each bot email?

**Comment by urkoperez16** [comment]
temp-mail.org

**Comment by orelt06** [comment]
> It is required when you create a Reddit account. If your account maker doesn’t give you or allow you to set one, you’re out of luck.

Do you have reddit account creator that do that?

**Comment by GilDev** [comment]
> Do you have reddit account creator that do that?

No and you will probably not find one here, it is outside of the scope of this project.

**Comment by orelt06** [comment]
> > Do you have reddit account creator that do that?
> 
> No and you will probably not find one here, it is outside of the scope of this project.

Do you have one outside of this project? Like the link i added

**Comment by Obelisx** [comment]
> > > Do you have reddit account creator that do that?
> > 
> > 
> > No and you will probably not find one here, it is outside of the scope of this project.
> 
> Do you have one outside of this project? Like the link i added

I recommend using Gmail.

If your mail is example@gmail.com, you can change it by writing e.xample@gmail.com/ex.ample@gmail.com/etc, and it will all send the accounts to the same inbox.

**Comment by Stifl** [comment]
>>> Do you have reddit account creator that do that?
>>No and you will probably not find one here, it is outside of the scope of this project.>Do you have one outside of this project? Like the link i added

You are probably not going to find one for free online.
It's not difficult to make such a "generator" yourself, but as others have said, it's out of the scope of this project.
