### ISSUE TITLE
panic: I could not decode the users.json file

### ISSUE THREAD

**Issue by 99a9** [Edouard127/reddit-placebot-2023#79]
hellp pls
![231](https://github.com/Edouard127/reddit-placebot-2023/assets/140398667/2398d857-1a58-4eff-b6fe-b8e8617d1ebe)

**Comment by 99a9** [comment]
![231](https://github.com/Edouard127/reddit-placebot-2023/assets/140398667/69902d29-1e27-4157-a436-c783a2496d46)

**Comment by 99a9** [comment]
![4321](https://github.com/Edouard127/reddit-placebot-2023/assets/140398667/ebc357c7-2a9d-46f8-95e6-64532f916023)

**Comment by GilDev** [comment]
There is a missing double quote after the second “username” and before the colon.
