### ISSUE TITLE
facing issue while executing build 

### ISSUE THREAD

**Issue by arreyaar** [Edouard127/reddit-placebot-2023#81]
artifact used
https://github.com/Edouard127/reddit-placebot-2023/suites/14507707367/artifacts/820255706

Windows-build.exe -minX=809 -minY=-234
Waiting for login to finish...
2023-07-24T17:11:44.319+0530    INFO    reddit-placebot-2023/client.go:50       Login successful        {"username": "vikashw"}
Login finished!
Waiting for board data
2023-07-24T17:11:45.720+0530    INFO    reddit-placebot-2023/board.go:50        Controller changed      {"username": "vikashw"}
Get "https://api.seeip.org/jsonip": socks connect tcp 127.0.0.1:9050->api.seeip.org:443: dial tcp 127.0.0.1:9050: connectex: No connection could be made because the target machine actively refused it.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0xf5a2f9]

goroutine 23 [running]:
main.listenForCircuit(0xf58e4a?, 0x0?)
        D:/a/reddit-placebot-2023/reddit-placebot-2023/util.go:89 +0x179
created by main.(*Client).Setup
        D:/a/reddit-placebot-2023/reddit-placebot-2023/client.go:245 +0x396

**Comment by 111nikol** [comment]
just start tor with the provided port address in the torcc file, this is what it should look like :
CircuitBuildTimeout 30
LearnCircuitBuildTimeout 0 
MaxCircuitDirtiness 30
SocksPort 9050
