### ISSUE TITLE
The placement of pixels isnt updating after 5 mins it's stuck.

### ISSUE THREAD

**Issue by 111nikol** [Edouard127/reddit-placebot-2023#84]
This is a great program, yet it still has some issues. I completely set the program up with different account, tor, ect, but when i launch it with powershell with the command provided, it logs in to the accounts, connects to the board, and starts placing pixels, after a few error from accounts not being able to place pixels due to "rate limit" (even if they still are able to place pixels if i do so manually), the whole program wont reset itself to place another batch of pixels its just stuck after the initial ones from the start of the program. Please help idk what is going on.

**Comment by Stifl** [comment]
Did you find a solution?
I know r/place is over for now, but I'm still trying to figure out, why my accounts weren't able to place pixels

**Comment by Edouard127** [comment]
> Did you find a solution?
> 
> I know r/place is over for now, but I'm still trying to figure out, why my accounts weren't able to place pixels

Reddit anti bot system
