### ISSUE TITLE
My ip got banned

### ISSUE THREAD

**Issue by lammamadelmanu** [Edouard127/reddit-placebot-2023#85]
Everytime I make a new account it gets immediatly shadowbanned. If I make one with a vpn, then it's useless because the script logins in the account without the vpn in my browser. Is there a way i can do this? if yes someone explain me please i beg you

**Comment by SuperPou1** [comment]
use a system wide vpn, such as wireguard

**Comment by lammamadelmanu** [comment]
I'm trying to use a proxychain on linux but it only works on the terminal with a specific command. Is there a software i can install that gives me like a permanent proxy, so that when the script opens the browser and logins in, it logins with the proxy.
