### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by amgdz** [Edouard127/reddit-placebot-2023#86]
hi, im new here : what can i do to fix that error ?
![image](https://github.com/Edouard127/reddit-placebot-2023/assets/140422023/1f3365b0-a193-44b0-b3dc-666fff504e6a)

**Comment by xcloudx12345** [comment]
i'm facing the same error

**Comment by xcloudx12345** [comment]
how you fix it?

**Comment by Obelisx** [comment]
> how you fix it?

Did you open Tor first? Make sure it's bootstrapped 100%.

**Comment by xcloudx12345** [comment]
thanks, i will try it
