### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Stater33** [Edouard127/reddit-placebot-2023#89]
![image](https://github.com/Edouard127/reddit-placebot-2023/assets/89501143/353e5dde-e94e-4a7d-b23f-70c5f3390762)

**Comment by QvixoteRoux** [comment]
I remember that for this one you need TOR running

**Comment by Obelisx** [comment]
> I remember that for this one you need TOR running

Tor is bootstrapped 100%, yet I still get this issue.
