### ISSUE TITLE
Pixel was not placed, or was placed somewhere else

### ISSUE THREAD

**Issue by Huugboy** [Edouard127/reddit-placebot-2023#90]
I've already confirmed this isn't a shadowban.

This is what happens:
- The script loads
- Worker tries to place pixel
- Something goes wrong ("Pixel was not placed, or was placed somewhere else")
- In very rare cases it does place a pixel, but it's the wrong color.

I'm currently testing with just a downwards line of 5 pixels, fully white hex(FFFFFF), in a bmp format.
I've tested both 24 and 32 bit BMP files. (Even 24 saved in OS/2 instead of windows)

I've tested multiple workers, and even just a single one.
I've also tested one of my non bot accounts.

Just for the sake of it, i've also completely re-cloned and rebuilt it.

Again let me reiterate, this isn't a shadow ban. None of the accounts are shadowbanned.
I can manually place pixels on them just fine, they can then be seen on other accounts just fine.
I've also ruled out that it's a problem with tor, since i can manually enter a tor browser and place a pixel with the accounts.

**Comment by r4ngu** [comment]
remember, im not a developer nor edouard so i cant fact check this correctly, but it seems like thats the problem

**Comment by Huugboy** [comment]
According to the code, #FFFFFF should be a valid color.

**Comment by r4ngu** [comment]
so, is that color visible on your pixel art or its another color?

**Comment by 111nikol** [comment]
We need Eduardo on this case, even chatgpt 4 is unable to find answers.

**Comment by LucasMucaz** [comment]
@Edouard127  @Edouard127  @Edouard127

**Comment by SuperPou1** [comment]
i still have the error

**Comment by Edouard127** [comment]
At this point It's not worth it to debug the issue
I don't even know if the program can actually work, but I assume so because there's a ton of people using it

**Comment by SuperPou1** [comment]
damn…

**Comment by yetAnother-throwaway-122** [comment]
> At this point It's not worth it to debug the issue I don't even know if the program can actually work, but I assume so because there's a ton of people using it

It can work. Currently using https://github.com/Edouard127/reddit-placebot-2023/pull/88 and the changes from Saiv46's PRs. It still throws the error on console but have checked some coords and the pixels were placed.

**Comment by SuperPou1** [comment]
im trying right now, i noticed that im getting ratelimited messages way faster than before, ill wait till it places and see if it works!

**Comment by SuperPou1** [comment]
nah, still doesn't work

**Comment by SuperPou1** [comment]
huh, seems like only one of my bots work, one that i just logged in to check
the rest of my accounts havent been used since the last r/place, should i check if they will work after i log in?

**Comment by Huugboy** [comment]
Re-cloned and rebuilt the code again after the latest commits.
I'm still getting the same error and also not seeing the pixels.
Is this even fixable?

**Comment by Stifl** [comment]
@Huugboy Sorry to ask this, as this is a bit off-topic, but:
How did you get your accounts to not be shadowbanned automatically?
I'm currently generating accounts using rotating IPs from Tor, e-mail verification, and a captcha solver.
I can join subreddits, but I can't place any pixels on the canvas (they just won't show up on the public canvas, only for the user until it refreshes).

I would love to help solve this/your issue, but at this point, there is no incentive to even try if I have no accounts.

**Comment by PhilippFoerster** [comment]
Was anyone able to find out the reason for this happening?
I am testing with one account that I can manually place pixel with, Reddit API returns success bot no pixels are placed :(
