### ISSUE TITLE
error after login

### ISSUE THREAD

**Issue by theFOLI** [Edouard127/reddit-placebot-2023#98]
Get "https://api.seeip.org/jsonip": socks connect tcp 127.0.0.1:9050->api.seeip.org:443: dial tcp 127.0.0.1:9050: connectex: No connection could be made because the target machine actively refused it.

**Comment by cereal-kitty** [comment]
https://github.com/Edouard127/reddit-placebot-2023/issues/30

**Comment by dpgh552345** [comment]
D:\New folder\reddit-placebot-2023-master>redditplacebot -minX=64 -minY=64
Waiting for login to finish...
2023-07-25T16:06:38.131+0700    INFO    reddit-placebot-2023/client.go:50       Login successful        {"username": "Huypham3105"}
Login finished!
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x723ab6]

goroutine 1 [running]:
main.(*Board).GetDifferentData(0xc0000bc280)
        D:/a/reddit-placebot-2023/reddit-placebot-2023/board.go:43 +0xb6
main.(*Worker).Run(0xc0000bc2c0)
        D:/a/reddit-placebot-2023/reddit-placebot-2023/worker.go:37 +0x58
main.main()
        D:/a/reddit-placebot-2023/reddit-placebot-2023/main.go:47 +0x5cf

**Comment by Edouard127** [comment]
I don't understand why people don't know how to use github
You're supposed to make an issue for your problems, not post an unrelated error into an issue, I will simply ignore it

**Comment by Edouard127** [comment]
Also why people don't check for the 100 DIFFERENT ISSUES
THERE HAS BEEN LIKE 20 ISSUES BECAUSE PEOPLE CAN'T READ 60 WORDS FOR SHIT
