### ISSUE TITLE
I'm getting a "panic: runtime error: invalid memory address or zero pointer reference" error, how can I fix it?

### ISSUE THREAD

**Issue by yavuzilyas** [Edouard127/reddit-placebot-2023#99]
I'm getting a "panic: runtime error: invalid memory address or zero pointer reference" error, how can I fix it? thanks

**Comment by thedankeststorm** [comment]
Recreate the user.json file. Type in username and password again. This seems to be happening after the program ran once and saved your tokens.

**Comment by yavuzilyas** [comment]
but doesnt work

**Comment by cereal-kitty** [comment]
PLEASE find in the closed issues FIRST... We had seen like more than ten same issues......
https://github.com/Edouard127/reddit-placebot-2023/issues/30

**Comment by Edouard127** [comment]
Please learn how to use github
I saw you asked the exact same question in a PULL REQUEST
